Уровень 0
Придумайте матрицы, которые обладают следующими свойствами:
a) диагональная, ортогональная, но не единичная(!):
b) верхнетреугольная, ортогональная:
c) нижнетреугольная, ортогональная:
d) матрица, у которой определитель = 1, и все элементы не равны 0:
P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:
m = np.array([[2, 2],
[1, 3]])
print(m)

Уровень 1:
Найдите спектральное разложение матрицы:
m = np.array([[1, 2],
[2,3]])
print(m)

Постройте зависимость качества восстановления рукописных цифр (MNIST) в зависимости
от различного количества компонент PCA. В качестве метрики различия предлагаю использовать MSE.

In [2]:
import numpy as np

 #### Придумайте матрицы, которые обладают следующими свойствами: a) диагональная, ортогональная, но не единичная(!)

In [24]:
m = np.diag([3,1,3])
print(m)

[[3 0 0]
 [0 1 0]
 [0 0 3]]


In [25]:
m2 = m.T

In [26]:
m2

array([[3, 0, 0],
       [0, 1, 0],
       [0, 0, 3]])

In [27]:
a1 = m@m2
a1

array([[9, 0, 0],
       [0, 1, 0],
       [0, 0, 9]])

In [28]:
a2 = m2@m
m2

array([[3, 0, 0],
       [0, 1, 0],
       [0, 0, 3]])

#### b) верхнетреугольная, ортогональная:

In [11]:
m = np.triu([[1,2,3],[4,5,6],[7,8,9]], -1)
print(m)

[[1 2 3]
 [4 5 6]
 [0 8 9]]


 #### d) матрица, у которой определитель = 1, и все элементы не равны 0

In [7]:
# Вычисление определителя матрицы в python
# import numpy as np
# a = np.array([ [2, 1], [4, 3] ])
# print(np.linalg.det(a))
# Определитель может быть вычислен только для матриц с одинаковым количеством строк и столбцов – квадратных матриц. 

In [17]:
A = np.array([[2,1],[2,1]])
A

array([[2, 1],
       [2, 1]])

In [18]:
np.linalg.det(A)

0.0

In [19]:
A = np.array([[1, 0, 0],[-1, 4, 0],[2, 6, 1]])
A

array([[ 1,  0,  0],
       [-1,  4,  0],
       [ 2,  6,  1]])

In [20]:
A.transpose()

array([[ 1, -1,  2],
       [ 0,  4,  6],
       [ 0,  0,  1]])

#### Создание ортонормированной(ортогональной) матрицы

In [30]:
from scipy.stats import ortho_group  # Requires version 0.18 of scipy

m = ortho_group.rvs(dim=3)
m

array([[ 0.30680894,  0.53576724, -0.78665223],
       [-0.84612517,  0.5320029 ,  0.03232809],
       [-0.4358216 , -0.65568771, -0.6165494 ]])

In [31]:
m.dot(m.T)

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [ ]:
from scipy.linalg import qr

n = 3
H = np.random.randn(n, n)
Q, R = qr(H)


print (Q)
print (Q.dot(Q.T))

In [ ]:
for i in m:
    m = ortho_group.rvs(dim=3)
    

In [36]:
Q[1][0]

0.016104155887358022

In [39]:
Q[2][0]

0.9124464551435394

In [40]:
Q[2][1]

0.2507005497432889

In [2]:
try:
    Q = ortho_group.rvs(dim=3)
except Q[2][1] == 0:
    print(Q) 
         


NameError: name 'Q' is not defined